name: shelf_demo
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

dependencies:
  flutter: 
    sdk: flutter
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  maps_toolkit: ^3.0.0
  device_info_plus: ^10.1.0
  barcode: ^2.2.6
  uuid: ^4.4.0
  flutter_map_toolkit: ^0.0.4
  http: 0.13.6
  dio: ^5.4.2+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
